name: "Sync with upstream on the 'current' branch"

on:
  schedule:
    - cron: '42/15 * * * *'
  workflow_dispatch:

concurrency:
  group: sysops-upstream-sync

jobs:
  pull:
    name: Sync with upstream
    runs-on: ubuntu-latest

    environment: sysops-upstream-sync

    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    env:
      UPSTREAM_SYNC_LOCAL_BRANCH: ${{ vars.UPSTREAM_SYNC_LOCAL_BRANCH }}
      UPSTREAM_SYNC_REMOTE_NAME: ${{ vars.UPSTREAM_SYNC_REMOTE_NAME }}
      UPSTREAM_SYNC_REMOTE_URL: ${{ vars.UPSTREAM_SYNC_REMOTE_URL }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ vars.UPSTREAM_SYNC_LOCAL_BRANCH }}

    - name: Add remote
      run: |
        [[ -n "${UPSTREAM_SYNC_REMOTE_NAME}" ]]
        [[ -n "${UPSTREAM_SYNC_REMOTE_URL}" ]]
        git remote add "${UPSTREAM_SYNC_REMOTE_NAME}" "${UPSTREAM_SYNC_REMOTE_URL}"
        git remote --verbose
        git config --show-scope --get-regexp ^ 2>&1 | sed 's/^/::debug::/' || true

    - name: Pull
      run: |
        [[ -n "${UPSTREAM_SYNC_REMOTE_NAME}" ]]
        git pull "${UPSTREAM_SYNC_REMOTE_NAME}"

    - name: Push
      run: |
        [[ -n "${UPSTREAM_SYNC_LOCAL_BRANCH}" ]]
        git push origin "${UPSTREAM_SYNC_LOCAL_BRANCH}"
